### ISSUE TITLE
Safemode after Upgrade via HACS

### ISSUE THREAD

**Issue by sgtsilver** [myleskeeffe/clear-theme-dark-vibrant#1]
Safemode was activated after updating via HACS

Error Message as follows:

2021-02-07 12:08:19 ERROR (SyncWorker_3) [homeassistant.util.yaml.loader] while parsing a block mapping
  in "/config/themes/clear-dark-vibrant/clear-dark-vibrant.yaml", line 5, column 3
expected <block end>, but found '<scalar>'
  in "/config/themes/clear-dark-vibrant/clear-dark-vibrant.yaml", line 39, column 33

**Comment by ehbush** [comment]
Same issue here. Found the issue was a missing backtick on line 36 of clear-dark-vibrant.yaml, from ther following commit:

https://github.com/myleskeeffe/clear-theme-dark-vibrant/commit/81a960be87ab865ec178a5c4666dd96c7485a2d3

**Comment by sgtsilver** [comment]
> Same issue here. Found the issue was a missing backtick on line 36 of clear-dark-vibrant.yaml, from ther following commit:
> 
> [81a960b](https://github.com/myleskeeffe/clear-theme-dark-vibrant/commit/81a960be87ab865ec178a5c4666dd96c7485a2d3)

Quickfix is to copy the yaml from the version before. Restart HA and it works fine.

**Comment by myleskeeffe** [comment]
Thankyou everyone!

I really dropped the ball here. I really should have tested that more thoroughly. Thankyou for your comments!

I'll make sure to enable notifications so if I do this again anytime soon I'll know about it much sooner. Also I'll make sure to test things out in a beta branch for a while before merging into master with a release. Fixed with v2.0.7 :)
